services:
  db:
    image: postgres:16
    container_name: doctor_postgres
    restart: always
    environment:
      POSTGRES_DB: DoctorDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - doctor_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: doctor_api
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=DoctorDB;Username=postgres;Password=1234
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"

volumes:
  doctor_postgres_data: